- more test against missing arguments, files, etc
Changed files:
    docbook2X-docbook2man -> 1.3

diff --git a/docbook2X-docbook2man b/docbook2X-docbook2man
--- a/docbook2X-docbook2man
+++ b/docbook2X-docbook2man
@@ -8,14 +8,14 @@
 DIR="/usr/share/docbook2X"
 SPEC=$DIR/docbook2man-spec.pl
 MKLINKS=$DIR/manpage_makelinks.pl
-
+PROGNAME=`basename $0`
 
 if [ $# -eq 0 ]; then
-        echo "$0: No input file given";
+        echo "$PROGNAME: No input file given";
         exit;
 fi
 if [ $# -gt 1 ]; then
-        echo "$0: Too many arguments";
+        echo "$PROGNAME: Too many arguments";
         exit;
 fi
 
@@ -24,37 +24,51 @@ if [ -x /usr/bin/onsgmls ]; then
 else if [ -x /usr/bin/nsgmls ]; then
         SP=nsgmls;              
 else
-        echo "$0: SGML parser missing";
+        echo "$PROGNAME: SGML parser missing";
         exit;
 fi
 fi
 
-rm -f manpage.links
+if [ ! -f "$1" ]; then
+        echo "$PROGNAME: Unable to open file $1";
+        exit;
+fi
+
+
+if [ -f manpage.links ]; then
+    echo "$PROGNAME: There is file \`manpage.links' in current dir. "\
+	 "I need to create temporary file \`manpage.links'. Please remove "\
+	 "existing file."
+    exit 2;
+fi
+
 $SP <"$1" |sgmlspl $SPEC
 
 LANGM=`awk -v IGNORECASE=1 -v RS=">[^<>]*<" '/^refentry/ {if(i=index($0,"lang=")) print substr($0,i+6,2); exit}' $1`
 REFNAME=`awk -v IGNORECASE=1 -v RS="<\/?refname( [^>]*)?>" '{getline; print $0; exit}' $1`
 if [ -z "$REFNAME" ]; then
-	echo "$0: <refname> element missing"
+	echo "$PROGNAME: <refname> element missing"
+	rm -f manpage.links
 	exit;
 fi
 SECTION=`awk -v IGNORECASE=1 -v RS="<\/?manvolnum( [^>]*)?>" '{getline; print $0; exit}' $1`
 MAINFILE=${REFNAME}.${SECTION}
 
 if [ ! -f "$MAINFILE" ]; then
-	echo "$0: Failed to convert manpage";
+	echo "$PROGNAME: Failed to convert manpage";
+	rm -f manpage.links
 	exit;
 fi
 
 # print main manpage name
-echo $MAINFILE
+echo "$MAINFILE"
 
 case "$LANGM" in
     "pl" )
-	mv $MAINFILE $MAINFILE.tmp
-        cat $MAINFILE.tmp |sed 's/^\.SH NAME$/\.SH NAZWA/' \
-                        |sed 's/^\.SH SYNOPSIS$/\.SH SK£ADNIA/' >$MAINFILE;
-	rm -f $MAINFILE.tmp;
+	mv "$MAINFILE" $MAINFILE."$PROGNAME".tmp
+        cat "$MAINFILE"."$PROGNAME".tmp |sed 's/^\.SH NAME$/\.SH NAZWA/' \
+                        |sed 's/^\.SH SYNOPSIS$/\.SH SK£ADNIA/' >"$MAINFILE";
+	rm -f "$MAINFILE"."$PROGNAME".tmp;
         ;;
 esac
 
@@ -62,10 +76,13 @@ esac
 $MKLINKS < manpage.links
 awk '{print $2}' manpage.links
 
-#rm -f manpage.links
+rm -f manpage.links
 
 
 # $Log$
+# Revision 1.2  2000/01/20 14:41:08  klakier
+# - I forgot to commit it ... I dont remember
+#
 # Revision 1.1  1999/12/29 15:59:47  klakier
 # - wrapper script for Steve Cheng's docbook2man-spec converter
 #  
